### ISSUE TITLE
BUG: add nodes failure

### ISSUE THREAD

**Issue by mond77** [labring/sealos#2295]
### Sealos Version

main

### How to reproduce the bug?

only a master of the cluster at the beginning
```
root@lin-master:/home/ubuntu# sealos add --nodes 10.35.128.110
2022-12-22T08:05:57 info start to scale this cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2c65d42]

goroutine 1 [running]:
github.com/labring/sealos/pkg/apply/processor.NewScaleProcessor({0x36d49f0, 0xc000568160}, {0xc00071b200, 0x2, 0x4}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...)
	/root/tmp/sealos/pkg/apply/processor/scale.go:264 +0x62
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).scaleCluster(0xc0004d0870, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0001fb550, 0x1, 0x1}, ...)
	/root/tmp/sealos/pkg/apply/applydrivers/apply_drivers_default.go:194 +0x518
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).reconcileCluster(0xc0004d0870)
	/root/tmp/sealos/pkg/apply/applydrivers/apply_drivers_default.go:150 +0x416
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).Apply(0xc0004d0870)
	/root/tmp/sealos/pkg/apply/applydrivers/apply_drivers_default.go:91 +0x298
github.com/labring/sealos/cmd/sealos/cmd.newAddCmd.func1(0xc000449200?, {0xc000718340?, 0x2?, 0x2?})
	/root/tmp/sealos/cmd/sealos/cmd/add.go:50 +0x47
github.com/spf13/cobra.(*Command).execute(0xc000449200, {0xc000718320, 0x2, 0x2})
	/root/gowork/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x4945c00)
	/root/gowork/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/gowork/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/labring/sealos/cmd/sealos/cmd.Execute()
	/root/tmp/sealos/cmd/sealos/cmd/root.go:46 +0x25
main.main()
	/root/tmp/sealos/cmd/sealos/main.go:27 +0x29
root@lin-master:/home/ubuntu# sealos add --nodes 10.35.128.110
Error: host 10.35.128.110:22 already joined
host 10.35.128.110:22 already joined
root@lin-master:/home/ubuntu# kubectl get nodes
NAME         STATUS   ROLES           AGE    VERSION
lin-master   Ready    control-plane   132m   v1.24.0
```
why this happen？

### What is the expected behavior?

succeed to add nodes

### What do you see instead?

add failure(panic)；
repeatly add shows that already joined；
but 'kubectl get nodes' shows that no new nodes added.

### Operating environment

```markdown
- Sealos version:main
- Docker version:
- Kubernetes version:
- Operating system:amd64
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by fengxsong** [comment]
Already fixed in the latest main branch.

**Comment by mond77** [comment]
👌i retry and succeed to add nodes. but why will this cause panic happen？

**Comment by fengxsong** [comment]
> 👌i retry and succeed to add nodes. but why will this cause panic happen？

it's a 🐛 by mistake. ):

**Comment by cuisongliu** [comment]
You can test it again. This problem was fixed yesterday.
