### ISSUE TITLE
BUG: Failed to reset master1 node

### ISSUE THREAD

**Issue by cnfzh66** [labring/sealos#3280]
### Sealos Version

v4.1.7

### How to reproduce the bug?

```
[root@k8s-node01 etc]# sealos reset --masters 192.168.178.51
are you sure to delete these nodes? Yes [y/yes], No [n/no] : y
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/labring/sealos/pkg/types/v1beta1.(*Cluster).GetRootfsImage(0xc0004c78c0, {0x0, 0x0})
        github.com/labring/sealos/pkg/types/v1beta1/cluster_args.go:138 +0x1bf
github.com/labring/sealos/pkg/runtime.(*KubeadmRuntime).getKubeVersionFromImage(...)
        github.com/labring/sealos/pkg/runtime/runtime_getter.go:51
github.com/labring/sealos/pkg/runtime.(*KubeadmRuntime).Validate(0xc000522cc0)
        github.com/labring/sealos/pkg/runtime/runtime.go:143 +0x4f
github.com/labring/sealos/pkg/runtime.newKubeadmRuntime(0xc0004c78c0, 0x0, 0x0)
        github.com/labring/sealos/pkg/runtime/runtime.go:116 +0x165
github.com/labring/sealos/pkg/runtime.NewDefaultRuntime(...)
        github.com/labring/sealos/pkg/runtime/runtime.go:128
github.com/labring/sealos/pkg/apply/processor.(*DeleteProcessor).Reset(0xc00059e840?, 0xc00059e901?)
        github.com/labring/sealos/pkg/apply/processor/delete.go:75 +0x3a
github.com/labring/sealos/pkg/apply/processor.DeleteProcessor.Execute({{0x3b734d0?, 0xc00059e840?}, {0x3b6b530?, 0xc00038a840?}}, 0xc00038a840?)
        github.com/labring/sealos/pkg/apply/processor/delete.go:51 +0x359
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).deleteCluster(0xc0004b3c70)
        github.com/labring/sealos/pkg/apply/applydrivers/apply_drivers_default.go:242 +0x51
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).Delete(0xc0004b3c70)
        github.com/labring/sealos/pkg/apply/applydrivers/apply_drivers_default.go:233 +0xe6
github.com/labring/sealos/cmd/sealos/cmd.newResetCmd.func1(0xc000806900?, {0xc0007e44a0?, 0x2?, 0x2?})
        github.com/labring/sealos/cmd/sealos/cmd/reset.go:54 +0x96
github.com/spf13/cobra.(*Command).execute(0xc000806900, {0xc0007e4480, 0x2, 0x2})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x4f6d6a0)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/labring/sealos/cmd/sealos/cmd.Execute()
        github.com/labring/sealos/cmd/sealos/cmd/root.go:47 +0x25
main.main()
        github.com/labring/sealos/cmd/sealos/main.go:27 +0x29
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
retry using sealos 4.2.0 ?

**Comment by cnfzh66** [comment]
> retry using sealos 4.2.0 ?

谢谢，可以了
