### ISSUE TITLE
BUG: brief description of the bug panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gitnehc** [labring/sealos#5054]
### Sealos Version

v5.0.0

### How to reproduce the bug?

1. sealos reset

### What is the expected behavior?

[root@master0 deployment]# sealos reset --force --masters=xx.xx.xx.xx
2024-09-09T14:08:17 info start to delete Cluster: master [10.105.5.233], node []
2024-09-09T14:08:17 info start to reset nodes: []
2024-09-09T14:08:17 info start to reset masters: [10.105.5.233:22]
2024-09-09T14:08:17 info start to reset node: 10.105.5.233:22
/usr/bin/kubeadm
[preflight] Running pre-flight checks
W0909 14:08:17.401140   12652 removeetcdmember.go:106] [reset] No kubeadm config, using etcd pod spec to get data directory
[reset] Deleted contents of the etcd data directory: /var/lib/etcd
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of directories: [/etc/kubernetes/manifests /var/lib/kubelet /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
2024-09-09T14:08:17 info Executing pipeline Bootstrap in DeleteProcessor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x359c0c6]

goroutine 1 [running]:
github.com/labring/sealos/pkg/bootstrap.NewContextFrom(0xc000614240)
	github.com/labring/sealos/pkg/bootstrap/context.go:71 +0x2c6
github.com/labring/sealos/pkg/bootstrap.New(0x0?)
	github.com/labring/sealos/pkg/bootstrap/bootstrap.go:49 +0x1d
github.com/labring/sealos/pkg/apply/processor.(*DeleteProcessor).UndoBootstrap(0xc00059f3e0, 0xc000614240)
	github.com/labring/sealos/pkg/apply/processor/delete.go:83 +0x28c
github.com/labring/sealos/pkg/apply/processor.DeleteProcessor.Execute({{0x44c6e10?, 0xc000b47350?}, {0x44bae80?, 0xc000627ba0?}}, 0xc000627ba0?)
	github.com/labring/sealos/pkg/apply/processor/delete.go:50 +0x35c
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).deleteCluster(0xc000496820)
	github.com/labring/sealos/pkg/apply/applydrivers/apply_drivers_default.go:265 +0x53
github.com/labring/sealos/pkg/apply/applydrivers.(*Applier).Delete(0xc000496820)
	github.com/labring/sealos/pkg/apply/applydrivers/apply_drivers_default.go:256 +0xe7
github.com/labring/sealos/cmd/sealos/cmd.newResetCmd.func1(0xc000522c00?, {0xc00059e300?, 0x2?, 0x2?})
	github.com/labring/sealos/cmd/sealos/cmd/reset.go:54 +0xa3
github.com/spf13/cobra.(*Command).execute(0xc000522c00, {0xc00059e2e0, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x5c6d560)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/labring/sealos/cmd/sealos/cmd.Execute()
	github.com/labring/sealos/cmd/sealos/cmd/root.go:49 +0x25
main.main()
	github.com/labring/sealos/cmd/sealos/main.go:27 +0x29

### Operating environment

```markdown
- Sealos version:v5.0.0
- Docker version:
- Kubernetes version:1.27.7
- Operating system:openeuler 22.03
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by yangxggo** [comment]
I don't really understand why sealos allows users to specify the master and node when using `sealos reset`. From the literal meaning, `reset` should delete all masters and nodes in the cluster. If you just want to delete one or some masters and nodes, why not use delete? If both `delete` and `reset` can specify nodes, isn't that redundant or repetitive?

**Comment by junlintianxiazhifulinzhongguo** [comment]
这个问题解决了吗，我也遇到了
